### ISSUE TITLE
✨ feat: 새 칼럼 생성 모달 (~7/2) 

### ISSUE THREAD

**Issue by JHmeatschool** [Sprint-Part3-14Team/14team-project#113]
## 📝설명
새로운 칼럼 추가하기 버튼을 클릭하면 새 칼럼 생성 모달이 뜹니다.
칼럼 이름을 입력해 생성할 수 있습니다.

![image](https://github.com/Sprint-Part3-14Team/14team-project/assets/162143999/9274f5ac-ec44-4769-bdd3-5d9e7a8e8f80)

## ✅TO-DO
- [ ] 새로운 칼럼 추가하기 클릭 시 모달창 띄우
- [ ] POST 요청 처리
- [ ] 중복된 칼럼 이름인 경우, 경고 문구
