### ISSUE TITLE
✨ feat: 칼럼관리 모달 (~7/2) 

### ISSUE THREAD

**Issue by JHmeatschool** [Sprint-Part3-14Team/14team-project#114]
## 📝설명
칼럼 설정 ⚙️버튼을 클릭하면 칼럼관리 모달이 뜹니다.
이름을 입력해 칼럼명을 변경할 수 있습니다.
삭제하기 클릭 시 경고 모달창이 뜹니다.
삭제 버튼 클릭 시 삭제할 수 있습니다.

![image](https://github.com/Sprint-Part3-14Team/14team-project/assets/162143999/f60b0478-4a94-4a70-99db-084db92d7492)

![image](https://github.com/Sprint-Part3-14Team/14team-project/assets/162143999/8e5f8b46-5430-4f1b-99cd-d0c824a0dfac)

## ✅TO-DO
- [ ] 칼럼 제목 옆 ⚙️ 버튼 클릭 시 모달창 띄우기 
- [ ] 삭제 버튼 클릭 시, "칼럼의 모든 카드가 삭제됩니다" 경고 모달창 띄우기 
- [ ] PUT 요청 처리 
- [ ] DELETE 요청 처리
