### ISSUE TITLE
💄design: 헤더 회원 정보 추가 (6/24)

### ISSUE THREAD

**Issue by ssseeo0** [Sprint-Part3-14Team/14team-project#12]
## 📝설명
사이드바에 회원 정보 추가 

## ✅TO-DO
- [x] 사이드바에 있는 로고 삭제
- [x] 로고 헤더로 이동 
- [x] 로그인한 회원정보 (프로필 이미지 + 닉네임) 
- [x] 프로필 이미지 + 사용자 이름 

## 💡기타
상단 네비게이션바에 있던 회원정보를 사이드바에 옮기는 것으로 변경
