### ISSUE TITLE
💄design: mydashboard 대시보드 리스트 디자인 구현 및 데이터 패칭 리팩토링(6/26)

### ISSUE THREAD

**Issue by ssseeo0** [Sprint-Part3-14Team/14team-project#56]
## 📝설명
데이터 패칭 후 대시보드 리스트 디자인 구현하는 작업입니다. 

## ✅TO-DO
- [x] 대시보드 카드 디자인 구현 및 컴포넌트 생성 
- [x] 데이터 패칭 로직 리팩토링 
- [x] 모바일 UI 구현
