### ISSUE TITLE
✨ feat: 재사용 가능한 드롭다운 구현 (~6/29)

### ISSUE THREAD

**Issue by CitrusSoda** [Sprint-Part3-14Team/14team-project#99]
## 📝설명
재사용 가능한 드롭다운을 구현합니다

## ✅TO-DO
- [ ] 선택 시 값을 보여주어야 할 것
- [ ] 선택 된 값이 무엇인지 보여주어야 할 것
- [ ] w-full을 주어 상위 div로 스타일링을 쉽게 해줄 것
